### ISSUE TITLE
Is this project training pipeline support IterableDataset

### ISSUE THREAD

**Issue by JohnHerry** [bfs18/e2_tts#10]
Thanks for the job. I saw that the dataset is mapping like dataset, it do not fit for large dataset trainging. Is this training pipeline runs if I change the dataset into IterableDataset?

**Comment by bfs18** [comment]
Hi @JohnHerry, thank you for your interest. The implemented dataset reads a list of files and splits them into buckets based on the file lengths. Additionally, dynamic bucketing batching is employed to improve training efficiency. Changing to IterableDataset works, but it may decrease training efficiency.

**Comment by JohnHerry** [comment]
Thank you for the help.

**Comment by JohnHerry** [comment]
And the dataloader design, why it takes direct pcm data instead of melspec? it will cost more memory
