### ISSUE TITLE
What is the input of the duration predictor?

### ISSUE THREAD

**Issue by JohnHerry** [bfs18/e2_tts#12]
Hi, I am sorry for can not understand the code about duration predictor, its input is just an `x`,  I do not know what does this mean. Is it a text token sequence? or something else?

**Comment by bfs18** [comment]
Hi @JohnHerry The duration predictor module takes the mean-pooled hidden representations from the text encoder as input, and predicts the length ratio between acoustic frames and phonemes.

**Comment by JohnHerry** [comment]
> Hi @JohnHerry The duration predictor module takes the mean-pooled hidden representations from the text encoder as input, and predicts the length ratio between acoustic frames and phonemes.

thank you very much.
