### ISSUE TITLE
Is the cosine scheduler preferable in this project?

### ISSUE THREAD

**Issue by JohnHerry** [bfs18/e2_tts#13]
Hi, I noticed that in this project, the cosine lr-schduler is used instead of noam or  other linear like. is it tested tobe preferable?

**Comment by bfs18** [comment]
Hi @JohnHerry , although I haven't experimented with NOAM scheduler or other linear learning rate schedules, empirical evidence suggests that cosine learning rate scheduling is more widely adopted in transformer-based model training.

**Comment by JohnHerry** [comment]
> Hi @JohnHerry , although I haven't experimented with NOAM scheduler or other linear learning rate schedules, empirical evidence suggests that cosine learning rate scheduling is more widely adopted in transformer-based model training.

thank you for the help.
