### ISSUE TITLE
about the orginization of training filelist

### ISSUE THREAD

**Issue by JohnHerry** [bfs18/e2_tts#14]
@bfs18,  hi, I am now confused by the train filelist of this project, from the dataset.py, the filelist should be formated as:   
```
sample_id|wav_path|text_token_path|....
```   
while from the bucket.py, the filelist should be formated as:   
```
wav_path|wav_duration|
```    
the class in the dataset.py is a subclass of someone in the bucket.py,   so which format is the right one that I format my traning input?

**Comment by bfs18** [comment]
Hi @JohnHerry 
> `sample_id|wav_path|text_token_path|....`

This is correct. 
https://github.com/bfs18/e2_tts/blob/380ac0f54b2e81d960ac9b473a0c1efafd74588e/rfwave/bucket.py#L294 In this line, duration is the last field.

**Comment by JohnHerry** [comment]
> Hi @JohnHerry
> 
> > `sample_id|wav_path|text_token_path|....`
> 
> This is correct.
> 
> https://github.com/bfs18/e2_tts/blob/380ac0f54b2e81d960ac9b473a0c1efafd74588e/rfwave/bucket.py#L294
> 
> In this line, duration is the last field.

Oh, sorry, I see, thank you very much.
