### ISSUE TITLE
Why there is a <BOS> token before the text token sequence?

### ISSUE THREAD

**Issue by JohnHerry** [bfs18/e2_tts#16]
Hi, @bfs18 ,
     I see in the code that every sample text will be given a <BOS> as the begining of the text sequence. In most AR-Token-LLM-TTS system, there should be a <SEP> between text part and audio token part,  but never a single <BOS> token needed.  infact the <BOS> token is not necessary in AR-Token-LLMs.     
    In the paper of E2-TTS, I did not see it need special position tokens like <BOS>,<EOS>, or <SEP>,  even when it is needed, I think it should be a <SEP> between phoneme token and mels, so why you design a <BOS> here ? Will this design get better performance?   
     and what about other transformer input sequence designes?  what is the best input sequence design in this E2_TTS project?  
thank you.

**Comment by bfs18** [comment]
Hi @JohnHerry It's a traditional design used in Tacotron and FastSpeech. The token corresponds to the initial silence.

**Comment by JohnHerry** [comment]
Thank you verfy much,  My train is ok now, and I did not use this specitail token.    
I had have bad  a train result, but it seems not  relevant to this token,  Thank you.
