### ISSUE TITLE
Inspired code ?

### ISSUE THREAD

**Issue by lumpidu** [bfs18/e2_tts#18]
Hi, just out of interest. Is your repository in any way inspired by https://github.com/lucidrains/e2-tts-pytorch or have you taken a look at this repository ?

It would be interesting to know the differences in training/results, etc.

**Comment by bfs18** [comment]
Hi @lumpidu These two codebases were independently developed. There was an interesting discussion about the differences and implementation details in this issue: https://github.com/lucidrains/e2-tts-pytorch/issues/25

**Comment by lumpidu** [comment]
Ah thanks @bfs18. Have gone through the issue. Very englightning.
