### ISSUE TITLE
请问如何提高E2_TTS的合成稳定性？

### ISSUE THREAD

**Issue by JohnHerry** [bfs18/e2_tts#19]
@bfs18  您好，我这里能够复现出一些效果了，听起来自然度还不错，但是合成稳定性不太好。同样的输入，多合成几次，每次听到的效果都不一样。 我这里已经设置了 python的random.seed, numpy.random.seed, torch.manual_seed,  torch.cuda.manual_seed等都设置为同一个固定的种子值，但是还是不能保证相同的输入，两次相邻合成的音频是一样的。请问怎么能保证合成效果的稳定可重现呢？    
第二个问题，E2这类NAR的大模型，是否也有类似 AR里一些top-K采样类似的手段，来让合成的效果更好呢？目前看还是存在合成的幻读，漏读，重复等问题的。语音自然度效果也不是很稳定。  
谢谢！

**Comment by bfs18** [comment]
@JohnHerry 在相同种子和调用次数下，随机数生成器会产生完全一致的序列，因此每次重置种子后的多次合成结果应该保持一致。要合成一次，重置一次种子。

增强稳定性比较好的办法是加数据，加模型规模。

**Comment by JohnHerry** [comment]
> @JohnHerry 在相同种子和调用次数下，随机数生成器会产生完全一致的序列，因此每次重置种子后的多次合成结果应该保持一致。要合成一次，重置一次种子。
> 
> 增强稳定性比较好的办法是加数据，加模型规模。

感谢，受教了！
另外看到[lucidrains的UNet实现版本](https://github.com/lucidrains/e2-tts-pytorch)里， 好像试图用EMA来做模型的参数调优。据说EMA算法确实有助于生成式模型的效果和稳定性。不知道对DiT架构模型是否同样有效呢？
