### ISSUE TITLE
支持多GPU训练吗

### ISSUE THREAD

**Issue by ABC0408** [bfs18/e2_tts#3]

**Comment by bfs18** [comment]
支持，lighting自动支持的，改一下配置，把devices都加到这里。但这个代码我没测过，有啥问题反馈一下。https://github.com/bfs18/e2_tts/blob/29aebf18158b68c3b2902df33241efb55ee11eb1/config/e2_tts.yaml#L97

**Comment by bfs18** [comment]
@ABC0408
https://github.com/bfs18/e2_tts/blob/2a3c19259aac46ff050de818a2947dd487f3772f/rfwave/experiment_e2.py#L68

这句改成
```
self.backbone = backbone
```

**Comment by ABC0408** [comment]
> @ABC0408
> 
> https://github.com/bfs18/e2_tts/blob/2a3c19259aac46ff050de818a2947dd487f3772f/rfwave/experiment_e2.py#L68
> 
> 这句改成
> 
> ```
> self.backbone = backbone
> ```

厉害，可以了👍
