### ISSUE TITLE
about ctx dim and vocab size in input

### ISSUE THREAD

**Issue by acul3** [bfs18/e2_tts#7]
hello @bfs18 

i using two phonemizer due multilinguality

my len phoneset is 126, 

i am planning to change the vocab size to 126

do i need to change ctx dim also?

**Comment by bfs18** [comment]
@acul3  You adjust the vocabulary size only. If you have 126 phonemes, you should set the vocabulary size to 127 to account for an extra padding token.

**Comment by acul3** [comment]
@bfs18 thanks for reply

btw my dataset is 1.9 sec to 30 sec audio,, using your initial config will be there a problem? (some filtering that i dont know of) , i am seeing 560 as max duration (i am assuming this is second?) ?


-----

i am training 1.5k hours multilingual, 800 hours eng,  700 hours ind

after 10 epoch (80k) the result give okay-ish result

ref audio:

https://github.com/user-attachments/assets/503d33c2-6705-455b-b11c-93f11c5e0bfa

gen audio:

https://github.com/user-attachments/assets/6fdba2f2-31d1-46a8-87d1-5410281c3b7b

the accent still not quite there, maybe train longer

**Comment by bfs18** [comment]
@acul3 Yes, the max_duration in the config is in seconds. You can modify it to fill up your GPU memory. Training for a longer duration will produce a better accent. The prompt audio should be 2 to 3 seconds long to achieve better results, as the min_context and max_context in the config are set to 200 and 300 frames, respectively.
